/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author sumes
 */
public class BusDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusDetails
     */
    public BusDetails() {
        initComponents();
        LoadData();
          Toolkit toolkit=getToolkit();
       Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        txtbusid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblbusid = new javax.swing.JLabel();
        lblSource1 = new javax.swing.JLabel();
        lblDestination1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblNoSeats = new javax.swing.JLabel();
        txtsource = new javax.swing.JTextField();
        txtbusid = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSave1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        dtcdate = new com.toedter.calendar.JDateChooser();
        btnnew = new javax.swing.JButton();
        lblprice = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnnew1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Add Bus Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 13, -1, -1));

        lblbusid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblbusid.setForeground(new java.awt.Color(255, 255, 255));
        lblbusid.setText("bus Id :");
        getContentPane().add(lblbusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 54, -1, -1));

        lblSource1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSource1.setForeground(new java.awt.Color(255, 255, 255));
        lblSource1.setText("Source :");
        getContentPane().add(lblSource1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 94, -1, -1));

        lblDestination1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDestination1.setForeground(new java.awt.Color(255, 255, 255));
        lblDestination1.setText("Destination :");
        getContentPane().add(lblDestination1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 134, -1, -1));

        lblDate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate1.setForeground(new java.awt.Color(255, 255, 255));
        lblDate1.setText("Date :");
        getContentPane().add(lblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time :");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 214, -1, -1));

        lblNoSeats.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblNoSeats.setText("No Of Seats :");
        getContentPane().add(lblNoSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 241, -1, -1));

        txtsource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsourceActionPerformed(evt);
            }
        });
        txtsource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsourceKeyPressed(evt);
            }
        });
        getContentPane().add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 92, 182, -1));

        txtbusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusidActionPerformed(evt);
            }
        });
        txtbusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusidKeyPressed(evt);
            }
        });
        getContentPane().add(txtbusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 52, 182, -1));

        txtDestination.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDestinationKeyPressed(evt);
            }
        });
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 132, 182, -1));

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        txttime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimeKeyTyped(evt);
            }
        });
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 212, 182, -1));

        txtseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatsActionPerformed(evt);
            }
        });
        txtseats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtseatsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtseatsKeyReleased(evt);
            }
        });
        getContentPane().add(txtseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 241, 182, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bus Id", "Source", "Destination", "Date", "Time", "No Of Seats", "price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 70, 457, 234));

        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 346, -1, -1));

        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 346, -1, -1));

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 346, -1, -1));
        getContentPane().add(dtcdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 172, 182, -1));

        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 346, -1, -1));

        lblprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblprice.setForeground(new java.awt.Color(255, 255, 255));
        lblprice.setText("price:");
        getContentPane().add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 272, -1, -1));

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpriceKeyPressed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 270, 182, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservation/3409297.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        btnnew1.setText("New");
        btnnew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnew1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 346, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    String dob=sdf.format(dtcdate.getDate());
                    String qry="update BusDetails set Source='"+txtsource.getText()+"',Destination='"+txtDestination.getText()+"',Date='"+dob+"',Time='"+txttime.getText()+"',NoOfSeats='"+txtseats.getText()+"',Price='"+txtprice.getText()+"' where BusId='"+txtbusid.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Record updated..");
                            
                              DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                            model.setRowCount(0);
                            LoadData();
                            clearControls();
                             btnSave1.setEnabled(true);
                             btnnew.setEnabled(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    String dob=sdf.format(dtcdate.getDate());
                    String qry="delete from BusDetails where BusId='"+txtbusid.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Record Deleted..");
                            LoadData();
                            clearControls();
                             btnSave1.setEnabled(true);
                             btnnew.setEnabled(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
       try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    String dob=sdf.format(dtcdate.getDate());  
                    
                    if(Integer.parseInt(txtseats.getText())<=20)
                    {
                    String qry="insert into BusDetails values('"+txtbusid.getText()+"','"+txtsource.getText()+"','"+txtDestination.getText()+"','"+dob+"','"+txttime.getText()+"','"+txtseats.getText()+"','"+txtprice.getText()+"')";
                            PreparedStatement st=con.prepareStatement(qry);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Record submitted");
                            
                            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                            model.setRowCount(0);
                            LoadData();
                            clearControls();}
                    else 
                    {
                         JOptionPane.showMessageDialog(null, "No. of seats are not greater than 20!");
                    }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        btnSave1.setEnabled(false);
        btnnew.setEnabled(false);
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        txtbusid.setText(model.getValueAt(i,0).toString());
        
        try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String qry="select * from BusDetails where BusId='"+txtbusid.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs= st.executeQuery();
                            if(rs.next())
                            {
                                txtsource.setText(rs.getString("Source"));
                                txtDestination.setText(rs.getString("Destination"));
                                dtcdate.setDate(rs.getDate("Date"));
                                txttime.setText(rs.getString("Time"));
                                txtseats.setText(rs.getString("NoOfSeats"));
                                txtprice.setText(rs.getString("Price"));
                            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void txtsourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsourceActionPerformed

    private void txtbusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusidActionPerformed

    private void txtbusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusidKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c))
        {
            txtbusid.setEditable(true);
        }
        else
        {
            txtbusid.setEditable(false);
        }
    }//GEN-LAST:event_txtbusidKeyPressed

    private void txtsourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsourceKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtsource.setEditable(true);
        }
        else
        {
            txtsource.setEditable(false);
        }
        
    }//GEN-LAST:event_txtsourceKeyPressed

    private void txtDestinationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinationKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtDestination.setEditable(true);
        }
        else
        {
            txtDestination.setEditable(false);
        }
    }//GEN-LAST:event_txtDestinationKeyPressed

    private void txtseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatsActionPerformed

    private void txtseatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtseatsKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)  && c!='-')
        {
            txtseats.setEditable(true);
        }
        else
        {
            txtseats.setEditable(false);
            
        }
        
        
    }//GEN-LAST:event_txtseatsKeyPressed

    private void txtpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) && c!='-')
        {
            txtprice.setEditable(true);
        }
        else
        {
            txtprice.setEditable(false);
        }
    }//GEN-LAST:event_txtpriceKeyPressed

    private void btnnew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnew1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnew1ActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
            Connection con=DriverManager.getConnection(url,user,pass);
            String qry="select isnull(Max(BusId),0)+1 as ino from BusDetails";
            PreparedStatement st=con.prepareStatement(qry);
            ResultSet rs= st.executeQuery();
            if(rs.next())
            {
                String s=rs.getString("ino");
                txtbusid.setText(s);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnewActionPerformed

    private void txtseatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtseatsKeyReleased
        // TODO add your handling code here:
     /*    char c=evt.getKeyChar();
        if(Character.isDigit(c)  && c!='-')
        {
            txtseats.setEditable(true);
        }
        else
        {
            txtseats.setEditable(false);
            
        } 
        if(txtseats.getText()=="20")
        {
            JOptionPane.showMessageDialog(null, "No. of seats are not greater than 20");
        }
        else
        {
        }*/
    }//GEN-LAST:event_txtseatsKeyReleased

    private void txttimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimeKeyPressed
        // TODO add your handling code here:
       
        char c=evt.getKeyChar();
         
             
        if(Character.isDigit(c))
        {
               txtbusid.setEditable(true);  
        }
        else
        {
            txtbusid.setEditable(false);
        }
        
       
    }//GEN-LAST:event_txttimeKeyPressed

    private void txttimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimeKeyTyped
        // TODO add your handling code here:
     /*    char c=evt.getKeyChar();
        {  
             
        if(Character.isDigit(c))
        {
            if(c<=24 && c>=0)
            {
               txtbusid.setEditable(true);  
            }
            else
            {
               JOptionPane.showMessageDialog(null, "Time need to be between 00 to 24 hours"); 
            }
           
        }
        else
        {
            txtbusid.setEditable(false);
        }
        } */
       
    }//GEN-LAST:event_txttimeKeyTyped
    public void clearControls()
    {
        txtbusid.setText("");
        txtsource.setText("");
        txtDestination.setText("");
        dtcdate.setDate(null);
        txttime.setText("");
        txtseats.setText("");
        txtprice.setText("");
    }
    
    public void LoadData()
    {
        try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String qry="select * from BusDetails";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs;
                            rs = st.executeQuery();
                           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnew1;
    private com.toedter.calendar.JDateChooser dtcdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDestination1;
    private javax.swing.JLabel lblNoSeats;
    private javax.swing.JLabel lblSource1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblbusid;
    private javax.swing.JLabel lblprice;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtbusid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtsource;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
