/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sumes
 */
public class SearchBus extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchBus
     */
    public SearchBus() {
        initComponents(); 
        fillCombo();
        fillCombo1();
          Toolkit toolkit=getToolkit();
       Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
         btnBook.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cmbSource = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDestination = new javax.swing.JComboBox<>();
        csDate = new com.toedter.calendar.JDateChooser();
        btnBook = new javax.swing.JButton();
        lblavailable = new javax.swing.JLabel();
        txtavailable = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Advance Bus Booking System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("*Search Bus Here*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 42, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bus Id", "Source", "Destination", "Date", "Time", "No of Seats", "price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 130, 398, 269));

        getContentPane().add(cmbSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 130, 100, -1));

        btnSearch.setForeground(new java.awt.Color(0, 255, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 250, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 136, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 173, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 210, -1, -1));

        getContentPane().add(cmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 170, 100, -1));
        getContentPane().add(csDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 210, -1, -1));

        btnBook.setForeground(new java.awt.Color(51, 51, 255));
        btnBook.setText("BookBus");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 303, -1, -1));

        lblavailable.setForeground(new java.awt.Color(255, 255, 255));
        lblavailable.setText("Available bus Id :");
        getContentPane().add(lblavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 96, -1, -1));
        getContentPane().add(txtavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 96, 73, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservation/5166950.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i=jTable2.getSelectedRow();
        TableModel model=jTable2.getModel();
        txtavailable.setText(model.getValueAt(i, 0).toString());
         try
      {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                   
                    String qry="select BusId from BusDetails where BusId='"+txtavailable.getText().toString()+"' ";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs=st.executeQuery(); 
                            while(rs.next())
                            {
                                txtavailable.setText(rs.getString("BusId"));
                            }
                           
                            //LoadData();
                            //clearControls();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
      }  
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here: 
        try
        {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    String dob=sdf.format(csDate.getDate());
                    String qry="select * from BusDetails where Source='"+cmbSource.getSelectedItem().toString()+"' and Destination='"+cmbDestination.getSelectedItem().toString()+"' and Date='"+dob+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs=st.executeQuery(); 
                            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                            //LoadData();
                            //clearControls();
                             btnBook.setEnabled(true);
           
                           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        String id=txtavailable.getText().toString();
        personalDetails pd=new personalDetails(id);
        JDesktopPane jd=getDesktopPane();
        jd.add(pd);
        this.dispose();
        pd.show();
    }//GEN-LAST:event_btnBookActionPerformed
  public void fillCombo()
  {
      try
      {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                   
                    String qry="select Distinct Source from BusDetails ";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs=st.executeQuery(); 
                            while(rs.next())
                            {
                                cmbSource.addItem(rs.getString("Source"));
                                
                            }
                           
                            //LoadData();
                            //clearControls();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
      }
  } 
   public void fillCombo1()
  {
      try
      {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                   
                    String qry="select Distinct Destination from BusDetails ";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs=st.executeQuery(); 
                            while(rs.next())
                            {
                                cmbDestination.addItem(rs.getString("Destination"));
                                
                            }
                           
                            //LoadData();
                            //clearControls();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
      }
  }
 
   
  
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbDestination;
    private javax.swing.JComboBox<String> cmbSource;
    private com.toedter.calendar.JDateChooser csDate;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblavailable;
    private javax.swing.JTextField txtavailable;
    // End of variables declaration//GEN-END:variables
}
