/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumes
 */
public class Ticket extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
       
    }

   

    Ticket(String mn, String Id) {
       initComponents();
       txtmobileNo.setText(mn);
       txtbusid.setText(Id);
       FetchData();
       FetchData2();
       NonEditable();
        jLabel7.setVisible(false);
       Toolkit toolkit=getToolkit();
       Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdbmale = new javax.swing.JRadioButton();
        txtfnm = new javax.swing.JTextField();
        rdbfemale = new javax.swing.JRadioButton();
        txtmnm = new javax.swing.JTextField();
        txtlnm = new javax.swing.JTextField();
        rsbother = new javax.swing.JRadioButton();
        txtsource = new javax.swing.JTextField();
        lblsource = new javax.swing.JLabel();
        txtdest = new javax.swing.JTextField();
        lbldest = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        lbltime = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        lblseats = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtmobileNo = new javax.swing.JTextField();
        txtbusid = new javax.swing.JTextField();
        lblBusid = new javax.swing.JLabel();
        txtseats12 = new javax.swing.JTextField();
        lblseats1 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ticket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 13, -1, -1));

        jLabel3.setText("First Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, -1));

        jLabel4.setText("Middle Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, -1));

        lblgender.setText("Gender :");
        getContentPane().add(lblgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 188, -1, -1));

        jLabel5.setText("Last Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 188, -1, -1));

        rdbmale.setText("Male");
        getContentPane().add(rdbmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 184, -1, -1));
        getContentPane().add(txtfnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 115, 150, -1));

        rdbfemale.setText("Female");
        getContentPane().add(rdbfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 185, -1, -1));
        getContentPane().add(txtmnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 150, 150, -1));
        getContentPane().add(txtlnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 185, 150, -1));

        rsbother.setText("other");
        getContentPane().add(rsbother, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 185, -1, -1));
        getContentPane().add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 311, 150, -1));

        lblsource.setText("source");
        getContentPane().add(lblsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 314, -1, -1));
        getContentPane().add(txtdest, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 350, 150, -1));

        lbldest.setText("destination");
        getContentPane().add(lbldest, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 353, -1, -1));

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 282, 150, -1));

        lbltime.setText("Time");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 285, -1, -1));
        getContentPane().add(txtseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 321, 150, -1));

        lblseats.setText("Total No of Seats");
        getContentPane().add(lblseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 324, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 390, 150, -1));

        jLabel13.setText("Email Id :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 118, -1, -1));

        lbldate.setText("Date");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 390, -1, -1));

        jLabel14.setText("Mobilen No :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 156, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Personal Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 115, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Bus Details");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, -1, -1));
        getContentPane().add(txtmobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 147, 150, -1));
        getContentPane().add(txtbusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 282, 150, -1));

        lblBusid.setText("Bus Id :");
        getContentPane().add(lblBusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 285, -1, -1));

        txtseats12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseats12ActionPerformed(evt);
            }
        });
        getContentPane().add(txtseats12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 150, -1));

        lblseats1.setText(" Seats");
        getContentPane().add(lblseats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 361, -1, -1));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 404, 150, -1));

        lblprice.setText("price");
        getContentPane().add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 396, -1, -1));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 437, 138, 74));

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 59, 460, 439));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservation/5166950.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 510));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void txtseats12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseats12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseats12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
           
            
             try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    String dob=sdf.format(jDateChooser1.getDate());
                    String qry="insert into BookTicket values('"+txtbusid.getText()+"','"+txtfnm.getText()+"','"+txtmobileNo.getText()+"','"+txtseats12.getText()+"','"+txtprice.getText()+"','"+dob+"')";
                            PreparedStatement st=con.prepareStatement(qry);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Record submitted");
                           
                   String qry1="select TicketId from BookTicket Where MobileNo='"+txtmobileNo.getText()+"'"; 
                   PreparedStatement st1=con.prepareStatement(qry1);
                   ResultSet rs=st1.executeQuery(); 
                   if(rs.next())
                   {
                       jLabel7.setText(rs.getString("TicketId"));
                   }
                   
          
                         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
            txtarea.setText(txtarea.getText()+"**********************\n");
            txtarea.setText(txtarea.getText()+"******Ticket******\n");
            txtarea.setText(txtarea.getText()+"Ticke ID="+jLabel7.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Name="+"  "+txtfnm.getText()+" "+txtmnm.getText()+" "+txtlnm.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Bus Id="+" "+txtbusid.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Route of Bus="+" "+txtsource.getText()+" TO "+txtdest.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Date="+" "+jDateChooser1.getDate()+"\n");
            txtarea.setText(txtarea.getText()+"Time of Bus Depatrure="+txttime.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Seats Booked="+" "+txtseats12.getText()+"\n");
            txtarea.setText(txtarea.getText()+"Price="+" "+txtprice.getText()+"\n");
            txtarea.setText(txtarea.getText()+"*********HAPPY JOURNEY*************");
            txtarea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
 public void FetchData()
    {
         try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String qry="select * from BusDetails where BusId='"+txtbusid.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs= st.executeQuery();
                            if(rs.next())
                            {
                                txtsource.setText(rs.getString("Source"));
                                txtdest.setText(rs.getString("Destination"));
                                jDateChooser1.setDate(rs.getDate("Date"));
                                txttime.setText(rs.getString("Time"));
                                txtseats.setText(rs.getString("NoOfSeats"));
                            
                            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
 public void FetchData2()
 {
    try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String qry="select * from TicketTbl where MobileNo='"+txtmobileNo.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                            ResultSet rs= st.executeQuery();
                            if(rs.next())
                            {
                                txtfnm.setText(rs.getString("FirstName"));
                                txtmnm.setText(rs.getString("MiddleName"));
                                txtlnm.setText(rs.getString("LastName"));
                                txtemail.setText(rs.getString("EmailId"));
                                txtseats12.setText(rs.getString("Seats"));
                                txtprice.setText(rs.getString("Price"));
                                String gender=rs.getString("Gender");
                                if(gender.equals("male"))
                                {
                                    rdbmale.setSelected(true);
                                }
                                 if(gender.equals("female"))
                                {
                                    rdbfemale.setSelected(true);
                                }
                                  if(gender.equals("other"))
                                {
                                    rsbother.setSelected(true);
                                }
                                  
                            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }  
 }
 
 public void NonEditable()
 {
     txtbusid.setEditable(false);
     txtdest.setEditable(false);
     txtemail.setEditable(false);
     txtfnm.setEditable(false);
     txtmnm.setEditable(false);
     txtlnm.setEditable(false);
     txtmobileNo.setEditable(false);
     txtprice.setEditable(false);
     txtseats.setEditable(false);
     txtseats12.setEditable(false);
     txtsource.setEditable(false);
     txttime.setEditable(false);
     jDateChooser1.setEnabled(false);
     rdbmale.setEnabled(false);
     rdbfemale.setEnabled(false);
     rsbother.setEnabled(false);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusid;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldest;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lblseats1;
    private javax.swing.JLabel lblsource;
    private javax.swing.JLabel lbltime;
    private javax.swing.JRadioButton rdbfemale;
    private javax.swing.JRadioButton rdbmale;
    private javax.swing.JRadioButton rsbother;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtbusid;
    private javax.swing.JTextField txtdest;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfnm;
    private javax.swing.JTextField txtlnm;
    private javax.swing.JTextField txtmnm;
    private javax.swing.JTextField txtmobileNo;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtseats12;
    private javax.swing.JTextField txtsource;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
