/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Class.forName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.security.util.Password;
import java.sql.*;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author sumes
 */
public class userlogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form userlogin
     */
    public userlogin() {
        initComponents();
          Toolkit toolkit=getToolkit();
       Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnloginuser = new javax.swing.JButton();
        lblUsernameUser = new javax.swing.JLabel();
        txtusernameUser = new javax.swing.JTextField();
        lblpassuser = new javax.swing.JLabel();
        txtpassUser = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("User Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 13, -1, -1));

        btnloginuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnloginuser.setForeground(new java.awt.Color(51, 255, 51));
        btnloginuser.setText("login");
        btnloginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnloginuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 223, -1, -1));

        lblUsernameUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsernameUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernameUser.setText("username");
        getContentPane().add(lblUsernameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 89, -1, -1));

        txtusernameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameUserActionPerformed(evt);
            }
        });
        txtusernameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameUserKeyPressed(evt);
            }
        });
        getContentPane().add(txtusernameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 87, 165, -1));

        lblpassuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpassuser.setForeground(new java.awt.Color(255, 255, 255));
        lblpassuser.setText("password");
        getContentPane().add(lblpassuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 154, -1, -1));
        getContentPane().add(txtpassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservation/3409297.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameUserActionPerformed

    private void btnloginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginuserActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String qry="select Name,contact from userDetails where Name='"+txtusernameUser.getText()+"' and contact='"+txtpassUser.getText()+"'";
                            PreparedStatement st=con.prepareStatement(qry);
                           ResultSet rs=st.executeQuery();
                           String Name=txtusernameUser.getText();
                           String Contact=txtpassUser.getText();
                           if(rs.next())
                           {
                               JOptionPane.showMessageDialog(null, "Login Successfull..");
                               SearchBus sb=new SearchBus();
                               JDesktopPane jd=getDesktopPane();
                               jd.add(sb);
                               this.dispose();
                               sb.show();
                           }
                           else
                           {
                               JOptionPane.showMessageDialog(null, "Incorrect password..");
                           }
                            
                           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnloginuserActionPerformed

    private void txtusernameUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameUserKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtusernameUser.setEditable(true);
        }
        else
        {
            txtusernameUser.setEditable(false);
        }
    }//GEN-LAST:event_txtusernameUserKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsernameUser;
    private javax.swing.JLabel lblpassuser;
    private javax.swing.JPasswordField txtpassUser;
    private javax.swing.JTextField txtusernameUser;
    // End of variables declaration//GEN-END:variables
}
