/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sumes
 */
public class userreg extends javax.swing.JInternalFrame {

    /**
     * Creates new form userreg
     */
    public userreg() {
        initComponents();
          Toolkit toolkit=getToolkit();
       Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblnm = new javax.swing.JLabel();
        lblgndr = new javax.swing.JLabel();
        lblcnt = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        txtcnr = new javax.swing.JTextField();
        rdbml = new javax.swing.JRadioButton();
        rdmFml = new javax.swing.JRadioButton();
        rdbOtr = new javax.swing.JRadioButton();
        btnsv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("User Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        lblnm.setForeground(new java.awt.Color(255, 255, 255));
        lblnm.setText("Enter Name :");
        getContentPane().add(lblnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 117, -1, -1));

        lblgndr.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblgndr.setForeground(new java.awt.Color(255, 255, 255));
        lblgndr.setText("Gender :");
        getContentPane().add(lblgndr, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 185, -1, -1));

        lblcnt.setForeground(new java.awt.Color(255, 255, 255));
        lblcnt.setText("contact :");
        getContentPane().add(lblcnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 149, -1, -1));

        txtnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnmKeyPressed(evt);
            }
        });
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 114, 151, -1));

        txtcnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnrActionPerformed(evt);
            }
        });
        txtcnr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnrKeyPressed(evt);
            }
        });
        getContentPane().add(txtcnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 150, 151, -1));

        buttonGroup1.add(rdbml);
        rdbml.setText("male");
        getContentPane().add(rdbml, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 181, -1, -1));

        buttonGroup1.add(rdmFml);
        rdmFml.setText("female");
        getContentPane().add(rdmFml, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 181, -1, -1));

        buttonGroup1.add(rdbOtr);
        rdbOtr.setText("other");
        getContentPane().add(rdbOtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 181, -1, -1));

        btnsv.setText("Save");
        btnsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsvActionPerformed(evt);
            }
        });
        getContentPane().add(btnsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 245, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservation/483921.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnrActionPerformed

    private void btnsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsvActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=RegistrationDB";
            String user="sa";
            String pass="123";
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String gender="";
                    if(rdbml.isSelected())
                    {
                        gender="Male";
                    }
                     if(rdmFml.isSelected())
                    {
                        gender="Female";
                    }
                       if(rdbOtr.isSelected())
                    {
                        gender="Other";
                    }
                     
                    String qry="insert into userDetails values('"+txtnm.getText()+"','"+txtcnr.getText()+"','"+gender+"')";
                            PreparedStatement st=con.prepareStatement(qry);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Record submitted");
                            
                            this.dispose();
                            
               
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsvActionPerformed

    private void txtnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnmKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtnm.setEditable(true);
        }
        else
        {
            txtnm.setEditable(false);
        }
    }//GEN-LAST:event_txtnmKeyPressed

    private void txtcnrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnrKeyPressed
        // TODO add your handling code here:
         String phone=txtcnr.getText();
        int lenght=phone.length();
        char c=evt.getKeyChar();
        if(c>='0' && c<='9')
        {
            if(lenght<10)
            {
                txtcnr.setEditable(true);
            }
            else
            {
                txtcnr.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtcnr.setEnabled(true);
            }
            else
            {
                txtcnr.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtcnrKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblcnt;
    private javax.swing.JLabel lblgndr;
    private javax.swing.JLabel lblnm;
    private javax.swing.JRadioButton rdbOtr;
    private javax.swing.JRadioButton rdbml;
    private javax.swing.JRadioButton rdmFml;
    private javax.swing.JTextField txtcnr;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables
}
